<?php
/**
 * Proxy API avec auto-renouvellement de clé
 */
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

// ============================================================
// CONFIGURATION
// ============================================================
$MASTER_SECRET = 'MonSecret2026Ultra$ecuris#789XYZ';
$isHttps = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443);
$scheme = $isHttps ? 'https://' : 'http://';
$httpHost = $_SERVER['HTTP_HOST'] ?? '127.0.0.1:8000';
$API_URL = $scheme . $httpHost . '/tiktok_live.php';
$KEY_FILE = __DIR__ . '/donnees/api_key.json';

// ============================================================
// FONCTION: Générer une nouvelle clé API
// ============================================================
function generateNewKey($masterSecret, $apiUrl, $keyFile) {
    error_log("[API-PROXY] Début génération nouvelle clé...");
    
    $data = [
        'action' => 'generate_key',
        'master_secret' => $masterSecret,
        'name' => 'Auto-generated by api_proxy - ' . date('Y-m-d H:i:s'),
        'expiration_days' => 365
    ];
    
    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    curl_setopt($ch, CURLOPT_TIMEOUT, 180);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 15);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    error_log("[API-PROXY] HTTP Code: $httpCode");
    
    if ($httpCode === 200) {
        $result = json_decode($response, true);
        if (isset($result['key'])) {
            $keyData = [
                'key' => $result['key'],
                'created_at' => time(),
                'expires_at' => time() + (365 * 24 * 60 * 60),
            ];
            
            // Créer le dossier si nécessaire
            $dir = dirname($keyFile);
            if (!is_dir($dir)) {
                mkdir($dir, 0755, true);
            }
            
            file_put_contents($keyFile, json_encode($keyData, JSON_PRETTY_PRINT));
            error_log("[API-PROXY] ✓ Clé sauvegardée dans: $keyFile");
            
            sleep(1);
            return $result['key'];
        }
    }
    
    error_log("[API-PROXY] ✗ Échec génération");
    return null;
}

// ============================================================
// FONCTION: Récupérer clé valide
// ============================================================
function getValidApiKey($masterSecret, $apiUrl, $keyFile) {
    if (file_exists($keyFile)) {
        $keyData = json_decode(file_get_contents($keyFile), true);
        
        if ($keyData && isset($keyData['key'])) {
            $expiresIn = $keyData['expires_at'] - time();
            $daysLeft = round($expiresIn / 86400);
            
            if ($expiresIn > (7 * 24 * 60 * 60)) {
                return $keyData['key'];
            }
            
            error_log("[API-PROXY] ⚠ Clé expire bientôt, régénération...");
        }
    } else {
        error_log("[API-PROXY] ⚠ Pas de fichier de clé, génération...");
    }
    
    return generateNewKey($masterSecret, $apiUrl, $keyFile);
}

// ============================================================
// TRAITEMENT
// ============================================================
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Méthode non autorisée']);
    exit;
}

$rawInput = file_get_contents('php://input');
$input = json_decode($rawInput, true);

if (json_last_error() !== JSON_ERROR_NONE) {
    http_response_code(400);
    echo json_encode(['error' => 'JSON invalide']);
    exit;
}

// Obtenir clé valide
$API_KEY = getValidApiKey($MASTER_SECRET, $API_URL, $KEY_FILE);

if (!$API_KEY) {
    http_response_code(500);
    echo json_encode(['error' => 'Impossible de générer une clé API valide']);
    exit;
}

$input['api_key'] = $API_KEY;

// Requête vers API
$ch = curl_init($API_URL);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($input));
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json',
    'X-API-Key: ' . $API_KEY
]);
curl_setopt($ch, CURLOPT_TIMEOUT, 90);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 15);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

// Retry si erreur auth
if ($httpCode === 401 || $httpCode === 403) {
    error_log("[API-PROXY] Clé rejetée, régénération...");
    
    if (file_exists($KEY_FILE)) {
        unlink($KEY_FILE);
    }
    
    $API_KEY = generateNewKey($MASTER_SECRET, $API_URL, $KEY_FILE);
    
    if ($API_KEY) {
        $input['api_key'] = $API_KEY;
        
        $ch = curl_init($API_URL);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($input));
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
            'X-API-Key: ' . $API_KEY
        ]);
        curl_setopt($ch, CURLOPT_TIMEOUT, 90);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 15);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
    }
}

http_response_code($httpCode);
echo $response;
?>